# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                    BetterShop                                                | #
# |                                                                                              | #
# |                       https://github.com/Huskehhh/BetterShop                                 | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
default-shop: "MAIN"